contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 63925cfd-bb18-4f66-80ce-a314cca058a6
inputs: []
name: d
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b807e83e-6d58-4560-8569-7261393efd48
      iscommand: false
      name: ""
      version: -1
    taskid: b807e83e-6d58-4560-8569-7261393efd48
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 460,
          "y": 0
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: d
      value:
        simple: d
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 0b500e22-8e6c-43cd-8cc4-4db7d3f12d98
      iscommand: false
      name: d
      script: Set
      type: regular
      version: -1
    taskid: 0b500e22-8e6c-43cd-8cc4-4db7d3f12d98
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 460,
          "y": 210
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 305,
        "width": 380,
        "x": 460,
        "y": 0
      }
    }
  }
