contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.0.0
    itemVersion: 1.16.29
    packID: MicrosoftDefenderAdvancedThreatProtection
    packName: Microsoft Defender for Endpoint
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: This playbook used generic polling to get machine action information.
id: Microsoft Defender Advanced Threat Protection Get Machine Action Status
inputs:
- description: ""
  key: machine_action_id
  playbookInputQuery: null
  required: false
  value: {}
name: Microsoft Defender Advanced Threat Protection Get Machine Action Status
outputs:
- contextPath: MicrosoftATP.MachineAction.ID
  description: The machine action ID
  type: string
- contextPath: MicrosoftATP.MachineAction.Type
  description: Type of the action
  type: string
- contextPath: MicrosoftATP.MachineAction.Scope
  description: Scope of the action
- contextPath: MicrosoftATP.MachineAction.Requestor
  description: The ID of the user that executed the action.
  type: string
- contextPath: MicrosoftATP.MachineAction.RequestorComment
  description: Comment that was written when issuing the action.
  type: string
- contextPath: MicrosoftATP.MachineAction.Status
  description: The current status of the command
  type: string
- contextPath: MicrosoftATP.MachineAction.MachineID
  description: The machine ID on which the action was executed.
  type: string
- contextPath: MicrosoftATP.MachineAction.ComputerDNSName
  description: The machine DNS name on which the action was executed
  type: string
- contextPath: MicrosoftATP.MachineAction.CreationDateTimeUtc
  description: The date and time when the action was created
  type: date
- contextPath: MicrosoftATP.MachineAction.LastUpdateTimeUtc
  description: The last date and time when the action status was updated
  type: date
- contextPath: MicrosoftATP.MachineAction.RelatedFileInfo.FileIdentifier
  description: The file identifier
  type: string
- contextPath: MicrosoftATP.MachineAction.RelatedFileInfo.FileIdentifierType
  description: 'The type of the file identifier with the possible values: "Sha1" ,"Sha256"
    and "Md5"'
  type: string
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e3affdb9-3767-4b46-8989-693a0d2c2f15
      iscommand: false
      name: ""
      version: -1
    taskid: e3affdb9-3767-4b46-8989-693a0d2c2f15
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 40
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      Ids:
        simple: ${inputs.machine_action_id}
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: id
      PollingCommandName:
        simple: microsoft-atp-list-machine-actions-details
      Timeout:
        simple: "60"
      dt:
        simple: MicrosoftATP.MachineAction(val.Status == "Pending" || val.Status ==
          "InProgress" ).ID
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      id: 767426ee-8220-4948-8102-f1ac19bb872b
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: 767426ee-8220-4948-8102-f1ac19bb872b
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      id:
        complex:
          root: inputs.machine_action_id
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Return the machine's actions. If you set an action id it will return the info on the specific action
        Filtering can be done only on one argument
      id: f8cf2cce-4eb5-43e5-83c7-55bd848e2b49
      iscommand: true
      name: Get machine action info
      script: '|||microsoft-atp-list-machine-actions-details'
      type: regular
      version: -1
    taskid: f8cf2cce-4eb5-43e5-83c7-55bd848e2b49
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 425,
        "width": 380,
        "x": 50,
        "y": 40
      }
    }
  }
